import type { ReactNode } from "react";
import { cn } from "@/lib/utils";
import type { Provenance } from "@/lib/sim/engine";

export type Tone = "ok" | "warn" | "crit" | "info" | "neutral";

const toneClasses: Record<Tone, string> = {
  ok: "bg-ok-soft text-ok border-ok/25",
  warn: "bg-warn-soft text-warn border-warn/25",
  crit: "bg-crit-soft text-crit border-crit/25",
  info: "bg-info-soft text-info border-info/25",
  neutral: "bg-muted text-muted-foreground border-border",
};

export function StatusPill({
  tone = "neutral",
  children,
  className,
  dot = true,
}: {
  tone?: Tone;
  children: ReactNode;
  className?: string;
  dot?: boolean;
}) {
  return (
    <span
      className={cn(
        "inline-flex items-center gap-1.5 rounded-full border px-2.5 py-0.5 text-xs font-semibold tracking-wide",
        toneClasses[tone],
        className,
      )}
    >
      {dot && <span className="size-1.5 rounded-full bg-current" />}
      {children}
    </span>
  );
}

const provLabel: Record<Provenance, string> = {
  measured: "MEASURED",
  calculated: "CALCULATED",
  model: "MODEL",
  simulated: "SIMULATED",
};

export function ProvenanceTag({ p, className }: { p: Provenance; className?: string }) {
  return (
    <span
      className={cn(
        "rounded-sm border border-border bg-surface px-1.5 py-px text-[10px] font-semibold tracking-widest text-muted-foreground",
        className,
      )}
    >
      {provLabel[p]}
    </span>
  );
}

export function Panel({
  title,
  subtitle,
  actions,
  children,
  className,
  bodyClassName,
}: {
  title?: ReactNode;
  subtitle?: ReactNode;
  actions?: ReactNode;
  children: ReactNode;
  className?: string;
  bodyClassName?: string;
}) {
  return (
    <section className={cn("panel flex flex-col overflow-hidden", className)}>
      {(title || actions) && (
        <header className="flex items-start justify-between gap-3 border-b border-border px-4 py-3">
          <div className="min-w-0">
            <h2 className="text-sm font-semibold text-foreground">{title}</h2>
            {subtitle && <p className="mt-0.5 text-xs text-muted-foreground">{subtitle}</p>}
          </div>
          {actions && <div className="flex shrink-0 items-center gap-2">{actions}</div>}
        </header>
      )}
      <div className={cn("flex-1 p-4", bodyClassName)}>{children}</div>
    </section>
  );
}

export function Metric({
  label,
  value,
  unit,
  hint,
  tone = "neutral",
  provenance,
  className,
}: {
  label: string;
  value: ReactNode;
  unit?: string;
  hint?: ReactNode;
  tone?: Tone;
  provenance?: Provenance;
  className?: string;
}) {
  const toneText: Record<Tone, string> = {
    ok: "text-ok",
    warn: "text-warn",
    crit: "text-crit",
    info: "text-info",
    neutral: "text-foreground",
  };
  return (
    <div className={cn("panel px-4 py-3", className)}>
      <div className="flex items-center justify-between gap-2">
        <span className="label-xs">{label}</span>
        {provenance && <ProvenanceTag p={provenance} />}
      </div>
      <div className={cn("mono-num mt-2 flex items-baseline gap-1 text-2xl font-semibold", toneText[tone])}>
        {value}
        {unit && <span className="text-sm font-medium text-muted-foreground">{unit}</span>}
      </div>
      {hint && <div className="mt-1 text-xs text-muted-foreground">{hint}</div>}
    </div>
  );
}

export function PageHeader({
  title,
  description,
  actions,
}: {
  title: string;
  description: string;
  actions?: ReactNode;
}) {
  return (
    <div className="flex flex-wrap items-end justify-between gap-4 border-b border-border pb-4">
      <div>
        <h1 className="text-xl font-semibold tracking-tight text-foreground">{title}</h1>
        <p className="mt-1 max-w-3xl text-sm text-muted-foreground">{description}</p>
      </div>
      {actions && <div className="flex items-center gap-2">{actions}</div>}
    </div>
  );
}

export function Bar({ value, tone = "info" }: { value: number; tone?: Tone }) {
  const bg: Record<Tone, string> = {
    ok: "bg-ok",
    warn: "bg-warn",
    crit: "bg-crit",
    info: "bg-info",
    neutral: "bg-muted-foreground",
  };
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-surface">
      <div
        className={cn("h-full rounded-full transition-all duration-500", bg[tone])}
        style={{ width: `${Math.max(0, Math.min(100, value * 100))}%` }}
      />
    </div>
  );
}

export function PrototypeNotice({ children }: { children?: ReactNode }) {
  return (
    <p className="rounded-md border border-border bg-surface px-3 py-2 text-xs text-muted-foreground">
      {children ??
        "Prototype output. Values are generated by a simulated engine model and are not certified, airworthiness-qualified, or validated against a physical engine."}
    </p>
  );
}
