/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosisRouteImport } from './routes/diagnosis'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as MissionRouteImport } from './routes/mission'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as TwinRouteImport } from './routes/twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosisRoute = DiagnosisRouteImport.update({
  id: '/diagnosis',
  path: '/diagnosis',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionRoute = MissionRouteImport.update({
  id: '/mission',
  path: '/mission',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinRoute = TwinRouteImport.update({
  id: '/twin',
  path: '/twin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/mission': typeof MissionRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/mission': typeof MissionRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnosis': typeof DiagnosisRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/mission': typeof MissionRoute
  '/telemetry': typeof TelemetryRoute
  '/twin': typeof TwinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnosis'
    | '/health'
    | '/history'
    | '/mission'
    | '/telemetry'
    | '/twin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnosis'
    | '/health'
    | '/history'
    | '/mission'
    | '/telemetry'
    | '/twin'
  id:
    | '__root__'
    | '/'
    | '/diagnosis'
    | '/health'
    | '/history'
    | '/mission'
    | '/telemetry'
    | '/twin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosisRoute: typeof DiagnosisRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  MissionRoute: typeof MissionRoute
  TelemetryRoute: typeof TelemetryRoute
  TwinRoute: typeof TwinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnosis': {
      id: '/diagnosis'
      path: '/diagnosis'
      fullPath: '/diagnosis'
      preLoaderRoute: typeof DiagnosisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission': {
      id: '/mission'
      path: '/mission'
      fullPath: '/mission'
      preLoaderRoute: typeof MissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twin': {
      id: '/twin'
      path: '/twin'
      fullPath: '/twin'
      preLoaderRoute: typeof TwinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosisRoute: DiagnosisRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  MissionRoute: MissionRoute,
  TelemetryRoute: TelemetryRoute,
  TwinRoute: TwinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
